# Site settings
title: Ansi Hotel
email: info@ansi-almyrida.gr
description: "Enjoy magnificent views from your balcony"
baseurl: ""
sass:
    sass_dir: _sass
collections:
- rooms
# Build settings
markdown: kramdown
permalink: pretty
