# Site settings
title: Ansi Hotel
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/ansi-jekyll"
sass:
    sass_dir: _sass
collections:
- rooms
# Build settings
markdown: kramdown
permalink: pretty
